#API routes
film_list:
  path: /api/film/
  defaults: { _controller: \App\Bundle\FilmBundle\Film\API\Controller\ListFilmsController::findAll }
  methods: [GET]

film_byId:
  path: /api/filmById/
  defaults: { _controller: \App\Bundle\FilmBundle\Film\API\Controller\ListFilmsController::findById }
  methods: [POST]

film_deleteById:
  path: /api/delete/film/
  defaults: { _controller: \App\Bundle\FilmBundle\Film\API\Controller\DeleteFilmController::execute }
  methods: [DELETE]

film_create:
  path: /api/create/film/
  defaults: { _controller: \App\Bundle\FilmBundle\Film\API\Controller\CreateFilmController::execute }
  methods: [POST]

film_update:
  path: /api/update/film/{id}/
  defaults: { _controller: \App\Bundle\FilmBundle\Film\API\Controller\UpdateFilmController::execute }
  methods: [PUT]

actor_list:
  path: /api/actor/
  defaults: { _controller: \App\Bundle\FilmBundle\Actor\API\Controller\ListActorsController::findAll }
  methods: [GET]

actor_byId:
  path: /api/actorById/
  defaults: { _controller: \App\Bundle\FilmBundle\Actor\API\Controller\ListActorsController::findById }
  methods: [POST]

actor_create:
  path: /api/create/actor/
  defaults: { _controller: \App\Bundle\FilmBundle\Actor\API\Controller\CreateActorController::execute }
  methods: [POST]

actor_update:
  path: /api/update/actor/{id}/
  defaults: { _controller: \App\Bundle\FilmBundle\Actor\API\Controller\UpdateActorController::execute }
  methods: [PUT]

actor_deleteById:
  path: /api/delete/actor/
  defaults: { _controller: \App\Bundle\FilmBundle\Actor\API\Controller\DeleteActorController::execute }
  methods: [DELETE]

#Web routes
ChangeLang:
    path: /{_locale}/changeLang/{lang}/{route}/{id}/
    defaults: { _controller: \App\Bundle\FilmBundle\Film\Controller\DefaultFilmController::changeLangAction }
    requirements:
        _locale: '%app.locales%'

showFilm:
  path: /{_locale}/showFilm/{id}/
  defaults: { _controller: \App\Bundle\FilmBundle\Film\Controller\ShowFilmController::showFilmAction }
  methods: [GET]

showActor:
  path: /{_locale}/showActor/{id}/
  defaults: { _controller: \App\Bundle\FilmBundle\Actor\Controller\ShowActorController::showActorAction }
  methods: [GET]
